cachepath: .cache
discord:
    token: <yours>
    channels:
     -  437954211557277709 #real
     -  878361616712880162 #test playlist

manual:
    mydiscover: [https://open.spotify.com/playlist/<yours>] 

playlists:
 -  name: default
    channels:
     -  437954211557277709
    norepeat: false
    filter:
        track: true
        album: true
    reverse: true

 -  name: testing
    channels:
     -  878361616712880162
    filter:
        playlist: all
        track: true
        album: true
    norepeat: true
    shuffle: 239847239749

 -  name: weekly
    filter:
        playlist: Discover Weekly
    norepeat: true
 -  name: mydiscover
    channels: [mydiscover]
    filter:
        playlist: all
    norepeat: true

spotify:
    cachetoken: true
    clientid: <yours>
    clientsecret: <yours>
    redirect_uri: http://localhost:<yours>

    playlists:
     -  id: <your spotify playlist id>
        sync: default
     -  name: Test Server
        sync: testing
     -  name: Weekly
        sync: weekly
     -  name: Discover Forever
        sync: mydiscover
        nodelete: true
